apps/compras/urls.py
from django.conf.urls import url
from .views import nueva_compra, compras, buscar_proveedor, buscarProductos, save_compra

urlpatterns = [
    url(r'^$', compras, name="all_compras"),
    url(r'^nuevacompra/$',
        nueva_compra, name='nuevacompra'),
    url(r'^nuevacompra/proveedor/$', buscar_proveedor, name="buscar_pro"),
    url(r'^nuevacompra/productos/$', buscarProductos, name="burcar_producto"),
    url(r'^nuevacompra/save/$', save_compra, name="savecompra")
    # url(r'^seleccionar/nuevacompra/(?P<pro>\w+)/save_compra/$',
    #     SaveCompra, name='savecompra'),



]

versalles/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from apps.dashboard import urls as dash_url
from apps.ventas import urls as ventas_url
from apps.compras import urls as compras_url
from apps.reportes import urls as reportes_url
from apps.contactos import urls as contactos_url
from apps.inventario import urls as inventario_url

urlpatterns = [
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include((dash_url,'dashboard'))),
    url(r'^ventas/', include((ventas_url,'ventas'))),
    url(r'^compras/', include((compras_url, 'compras'))),
    url(r'^reportes/', include((reportes_url, 'reportes'))),
    url(r'^contactos/', include((contactos_url, 'contactos'))),
    url(r'^inventario/', include((inventario_url, 'inventario'))),
]

apps/compras/models.py
from django.db import models
from ..ventas.models import Producto, Vivero


class Proveedor(models.Model):
    identificacion = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=50)
    telefono = models.IntegerField()
    direccion = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'

    def __str__(self):
        return self.nombre


class Compra(models.Model):
    codigo = models.IntegerField(primary_key=True)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=False)
    vivero = models.ForeignKey(Vivero, on_delete=models.CASCADE)


class DetalleCompra(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    valor_compra = models.IntegerField()
    iva = models.IntegerField()
    valor_neto = models.IntegerField()
    descuento = models.IntegerField(null=True)

apps/compras/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from ..ventas.models import Vivero
from ..inventario.models import Almacen
from .models import Proveedor, Compra, DetalleCompra, Producto
from django.db.models import Q
import json


def compras(request):
    template_name = 'compras/allcompras.html'
    data = DetalleCompra.objects.extra(
        select={'total': 'SELECT sum(compras_detallecompra.valor_neto)  FROM compras_detallecompra WHERE compras_detallecompra.compra_id = compras_compra.codigo',
                }).select_related(
        'compra',
        'compra__vivero',
        'compra__proveedor').filter(
        compra__vivero_id=request.session['vivero']).distinct(
        'compra_id')

    fact = [{
        'id': res.compra.pk,
        'codigo': res.compra.codigo,
        'fecha': str(res.compra.fecha),
        'identificacion': res.compra.proveedor.identificacion,
        'nombre': res.compra.proveedor.nombre,
        'total': res.total,
    }for res in data]
    return render(request, template_name, {'data': json.dumps(fact)
                                           })


def nueva_compra(request):
    template_name = 'compras/nueva_compra.html'
    return render(request, template_name)


def buscar_proveedor(request):
    data = request.body.decode('utf-8')
    cliente = Proveedor.objects.all().filter(
        Q(nombre__icontains=data) | Q(identificacion__icontains=data))[:5]
    items = [{
        'id': res.pk,
        'nombre': res.nombre,
        'iden': res.identificacion

    }for res in cliente]
    return JsonResponse({'data': items}, safe=True)


def buscarProductos(request):
    dta = request.body.decode('utf-8')
    otra = json.loads(dta)
    prods = Producto.objects.select_related(
        'id_presentacion').filter(
            nombre__icontains=otra['valinput'], vivero_id=request.session['vivero'])[:9]
    data = [{
            'id': res.pk,
            'nombre': res.nombre,
            'iva': res.iva_porce,
            'precio': res.valor_real_compra,
            'presentacion': res.id_presentacion.tipo

            }for res in prods]
    return JsonResponse({'data': data}, safe=False)


def save_compra(request):
    data = request.body.decode('utf-8')
    datos = json.loads(data)
    f = Compra(codigo=datos['compra']['numero'],
               fecha=datos['compra']['fecha'], vivero_id=request.session['vivero'], proveedor_id=datos['cliente']['id'])

    f.save()
    for res in datos['datos']:
        val_iva = ((int(res['iva']) + 100) / 100) * \
            (int(res['precio']) * int(res['cantidad']))
        DetalleCompra.objects.create(
            compra_id=f.codigo, producto_id=res['id'], cantidad=int(res['cantidad']), valor_compra=int(res['precio']), iva=val_iva - (int(res['precio']) * int(res['cantidad'])), valor_neto=val_iva)
        stock = Almacen.objects.get(
            producto_id=res['id'], vivero_id=request.session['vivero'])

        rest = int(stock.stock) + int(res['cantidad'])
        stock.stock = rest
        stock.save()
    return HttpResponse(content="registro gurdado", status=200)

templates/compras/allcompras.html
{% extends "base.html" %} {% block title %}Compras{% endblock %} {% load static from staticfiles %} {% block content %} {% csrf_token %}
<div class="ui grid container">

  <div class="wide column border_links">
    <div class="grid_bar">
      <div class="links_bar">
        <a href="{% url 'ventas:allfacturas' %}" class="title-nav-link ">Compras</a>
      </div>

    </div>

  </div>
</div>
<div class="ui grid container">
  <div class="grid_bar">
    <div class="four column">
      <a href="{% url 'compras:nuevacompra'%}" class="ui primary button btn">Nueva Compra</a>
    </div>
  </div>

</div>
<section class="ui grid container">
  <div class="grid_bar">
    <div class="wide sixteen column" id="id_facturas">
      {% comment %}
      <table class="ui celled structured small table">
        <thead>
          <tr>
            <th>Número</th>
            <th>Creación</th>
            <th>Vencimiento</th>
            <th>Cliente</th>
            <th>Nombre</th>
            <th>Total</th>
            <th>Pagado</th>
            <th>Por Pagar</th>
            <th>Estado</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody id="TableFact">

        </tbody>
        <tfoot>
          <tr>
            <th colspan="7">
              <div class="ui right floated" id="pagging">

              </div>
            </th>
          </tr>
        </tfoot>

      </table> {% endcomment %}
      <div class="ui modal" id="modalPago">
        <i class="close icon"></i>
        <div class="header">
          Ingresar Pago Factura No. [[pago.factura]]
        </div>
        <div class="image content">

          <div class="description">
            <div class="ui form">
              <div class="inline fields">
                <div class="eight wide field">
                  <label>Valor Pago</label>
                  <input v-model="pago.valor" type="number" placeholder="" required>
                </div>

              </div>
            </div>
          </div>
        </div>
        <div class="actions">
          <div class="ui black deny button">
            Cancelar
          </div>
          <div class="ui positive right labeled icon button" @click="savePago">
            Guardar Pago
            <i class="checkmark icon"></i>
          </div>
        </div>
      </div>

      <div>
        <vue-good-table title="" :columns="columns" :rows="rows" :paginate="true" :lineNumbers="true" styleClass="ui basic table">
          <template slot="table-row" scope="props">
          <td class=" ">[[props.row.codigo]]</td>
          <td class=" ">[[props.row.fecha]]</td>
          <td class=" ">[[props.row.identificacion]]</td>
          <td class=" ">[[props.row.nombre]]</td>
          <td class=" ">[[moneda(props.row.total)]]</td>

         <td>
            {% comment %} <div class="ui icon bottom top right pointing dropdown button icon_action ">
            <i class="caret down icon"></i>
            <div class="menu">
              <a class="item" :href="'/ventas/facturas/detallefac/'+ props.row.codigo">Ver</a>
              <a class="item" @click="modalPago(props.row.codigo)" v-bind:class="[(props.row.estado=='cerrada' || props.row.estado=='anulada' ) ? 'disabled':'']">Agregar Pago</a>
              {% if user.is_superuser %}
                <div class="item" @click="showCancel(props.row.codigo)" :class="[(props.row.estado=='cerrada' || props.row.estado=='anulada' ) ? 'disabled':'']">Anular</div>
              {% endif %}


            </div>
          </div> {% endcomment %}
          </td>
        </template>

        </vue-good-table>
      </div>


    </div>
  </div>
</section>
<div class="ui basic modal" id="cancelModal">
  <div class="ui icon header">
    <i class="archive icon"></i> Anular Facturas
  </div>
  <div class="content">
    <p>
      ¿Está seguro de que desea anular la factura de venta?</p>
  </div>
  <div class="actions">
    <div class="ui red basic cancel inverted button">
      <i class="remove icon"></i> No
    </div>
    <button class="ui green ok inverted button" v-bind:click="cancelFactura">
      <i class="checkmark icon"></i> Si
    </button>
  </div>
</div>
<div class="ui basic modal" id="deleteModal">
  <div class="ui icon header">
    <i class="archive icon"></i> Eliminar Facturas
  </div>
  <div class="content">
    <p>
      ¿Está seguro de que desea eliminar la factura de venta?</p>
  </div>
  <div class="actions">
    <div class="ui red basic cancel inverted button">
      <i class="remove icon"></i> No
    </div>
    <div class="ui green ok inverted button">
      <i class="checkmark icon"></i> Si
    </div>
  </div>
</div>
{% endblock %} 

{% block js %}

<script type="text/javascript">
  let data = JSON.parse('{{data|safe}}')
</script>
<script type="text/javascript" src="{% static 'js/compras/compras.js' %}"></script>


{% endblock %}

templates/compras/nueva_compra.html
{% extends "base.html" %} {% load static from staticfiles %} {% block title %}Nueva Compra{% endblock title %} {% block content %} {% csrf_token %}
<div class="ui grid container">

  <div class="wide column">
    <div class="grid_bar">
      <div class="links_bar">
        <a href="{% url 'compras:all_compras' %}" class="title-back-link">
          <i class="angle left icon   icon-left"></i>
          Compras
        </a>
      </div>
    </div>

  </div>
</div>

<div class="ui grid container" id="app">
  <div class="grid_bar">
    <div class="six wide column">
      <h1 class="title-bar-factura">Nueva compra</h1>
    </div>
    <div class="wide column" id="newInvoice">
      <div class="invoice-border">
        <h3 class="title-invoice">Proveedor y fechas</h3>
        <form class="ui form" autocomplete="off" v-on:submit.prevent>

          <div class="fields">
            <div class="six wide field">
              <label for="" class="label-form">Proveedor</label>
              <div class="ui search">
                <div class="ui icon input">

                  <input v-on:keyup="buscar_pro" v-model="text" class="prompt" type="text" placeholder="Buscar...">
                  <i class="search icon"></i>

                </div>
                 <div class="results transition" :class="{'visible':client.length , 'hidden': !client.length }">
                  <a @click="selectClient(index)" v-for="(cliente,index) in client" class="result">
                    <div class="content">
                      <div class="title" v-text="cliente.nombre"></div>
                      <div class="description" v-text="cliente.iden"></div>
                    </div>
                  </a>
                </div> 
              </div>
            </div>
            <div class="four wide field">
            </div>
            <div class="three wide required field">
              <label for="" class="label-form">Numero Factura</label>
              <input v-model="info.compra.numero" type="text" name="" value="">
            </div>
            <div class="three wide required field">
              <label for="" class="label-form">Fecha Factura </label>
              <input type="date" v-model="info.compra.fecha" name="" value="">
            </div>
          </div>



          <div class="fields">
            <div class="six wide  field">
              <label for="" class="label-form">Indentificación</label>
              <input :value="info.cliente.iden"  type="text" name="ident" readonly required>
            </div>
            <div class="four wide field"></div>
            <div class="six wide field">
              <label for="" class="label-form">Notas</label>
              <textarea name="name" rows="5" cols="50"></textarea>
            </div>
          </div>
          <div class="products-border">

          </div>
          <h3 class="title-invoice">Linea de productos</h3>
          <div class="fields">

            
          </div>
          <div class="fields">
            <div class="six wide field">
              <div class="ui fluid search">
                <div class="ui icon input">
                  <input v-on:keyup="buscarProducto" v-model="producto" class="prompt" type="text" placeholder="Buscar...">
                  <i class="search icon"></i>
                </div>
                <div class="results transition" v-bind:class="{'visible':productos.length , 'hidden': !productos.length }">
                  <a class="result" @click="selectProduct(index)" v-for="(product ,index) in productos">
                    <div class="content">
                      <div class="title" v-text="product.nombre"></div>
                      <div class="description" v-text="product.presentacion"></div>
                      <div class="price" v-text="product.precio"></div>
                    </div>
                  </a>
                </div>
              </div>
            </div>
          </div> 
          
          <div class="fields">
            <div class="two wide required field">
              <label for="" class="label-form">Codigo</label>
              <input id="id_codigo" type="text" name="name" value="" readonly :value="valuesProduct.id">
            </div>
            <div class="six wide  required field">
              <label for="" class="label-form">Producto</label>
              <input id="id_producto" type="text" name="name" value="" readonly :value="valuesProduct.nombre">
            </div>
            <div class="two wide required field">
              <label for="" class="label-form">IVA</label>
              <input id="id_iva" type="text" name="name" value="" readonly :value="valuesProduct.iva">
            </div>
            <div class="three wide required  field">
              <label for="" class="label-form">Precio</label>
              <input id="id_precio" type="number" name="name" :value="valuesProduct.precio" v-model="valuesProduct.precio">
            </div>
            <div class="three wide required field">
              <label for="" class="label-form">Cantidad</label>
              <input id="id_cantidad" type="number" name="name" :value="valuesProduct.cantidad" v-model="valuesProduct.cantidad">
            </div>
          </div>
          <div class="fields aligning right">
            <div class="two field ">
              <button v-on:click="charge" class="ui  button btn">
                  Agregar
              </button>
            </div>
          </div>
          <div class="products-border">

          </div> 
          
          <div class="wide field">
            <table class="ui padded basic table bar_table">
              <thead>
                <tr>
                  <th>Codigo</th>
                  <th>Producto</th>
                  <th>Valor U</th>
                  <th>IVA</th>
                  <th>Cantidad</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="(data,index) in info.datos">
                  <td v-text="data.id"></td>
                  <td v-text="data.nombre"></td>
                  <td v-text="data.precio"></td>
                  <td v-text="data.iva"></td>
                  <td v-text="data.cantidad"></td>
                  <td>
                    <button @click="deleteRow(index)" class="ui icon button btn">
                        <i class="remove icon"></i>
                    </button>
                  </td>
                </tr>
              </tbody>



            </table>
          </div>
          {% verbatim %}

          <div class="products-border">

          </div>
          <div class="fields">
            <div class="eight wide field">
              <h3 class="title-invoice">Totales</h3>
            </div>
            <div class="four wide field">
              <span>Subtotal</span>
              <span id="id_sub" class="label float invoice-tot">${{subtotal}}</span>
            </div>
          </div>
          <div class="fields">
            <div class="eight wide field">

            </div>
            <div class="four wide field">
              <span>IVA</span>
              <span id="id_iv" class="label float invoice-tot">${{subiva}}</span>
            </div>
          </div>
          <div class="fields">
            <div class="eight wide field">

            </div>
            <div class="four wide field">
              <span>Total</span>
              <span id="id_tot" class="label float">${{tota}}</span>
            </div>
          </div>
          {% endverbatim %}
          <div class="products-border">

          </div>
          
          <div class="products-border">

          </div>
          <div class="six wide field">
            <button   @click="saveCompra" class="ui   button btn">
              Guardar
            </button>
          </div>

      </div>



      </form>
    </div>
  </div>
</div>








{% endblock content %} {% block js %}


<script  src="{% static 'js/compras/proveedores.js'%}"></script>
<script type="text/javascript" src="{% static 'js/moneda.js'%}"></script>
{% endblock js %}